on:
  push:
    tags:
      - '*'

name: Publish to Crates.io

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package
        run: cargo package --verbose
      - name: Dry Run
        run: cargo publish --dry-run --verbose
      - name: Publish
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
